# Master Makefile
# by Christoph Champ [started: 2006-10-12]
#include /home/champ/bin/makefiles/Makeconfig
#include /home/champ/bin/makefiles/paths.mk
#include /home/champ/bin/makefiles/general.mk
#include /home/champ/bin/makefiles/zdb.mk
#include /home/champ/bin/makefiles/cbs.mk
#include /home/champ/bin/makefiles/baker.mk
include /home/champ/bin/makefiles/converters.mk
