# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    [ -e "$HOME/.dircolors" ] && DIR_COLORS="$HOME/.dircolors"
    [ -e "$DIR_COLORS" ] || DIR_COLORS=""
    eval "`dircolors -b $DIR_COLORS`"
    alias ls='ls --color=auto'
fi

test -s ~/.alias && . ~/.alias || true

## Christoph's additions

# Do not put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth
export HISTSIZE=1000000
export HISTFILESIZE=1000000
export HISTTIMEFORMAT='%F %T ' # add timestamp to history
alias h1='history 10'
alias h2='history 20'
alias h3='history 30'
shopt -s histappend

export PATH=/home/champ/bin:$PATH
export VISUAL=vim
export EDITOR=/usr/bin/vim
export GIT_EDITOR=/usr/bin/vim
export SVN_EDITOR=/usr/bin/vim
export PYTHONWARNINGS="default"
export MTR_OPTIONS=-t  # force ncurses view on mtr
#export LESS='-R'
#export LESSOPEN="|~/.lessfilter %s"
#export LESSCOLORIZER=/usr/bin/pygmentize

#alias lpr='lpr -P Rollright860'
alias ll='ls -lXhp --color=auto'
alias lt='ls -lhpXtr --color=auto'
alias rm='rm -i'
alias shred='shred -xvzu' # Warning! Completey destroys file(s)!
alias zp='zypper'
alias psc='ps xawf -eo pid,user,cgroup,args'
alias t='/home/champ/bin/todo.sh'
alias rot13="tr '[A-Za-z]' '[N-ZA-Mn-za-m]'"
complete -F _todo t
# Nifty extras
alias webshare='python -c "import SimpleHTTPServer;SimpleHTTPServer.test()"'
alias servethis="python -c 'import SimpleHTTPServer; SimpleHTTPServer.test()'"
alias pypath='python -c "import sys; print sys.path" | tr "," "\n" | grep -v "egg"'
alias pycclean='find . -name "*.pyc" -exec rm {} \;'
alias pymods='python -c "import sys; sys.path = sys.path[1:]; import django; print(django.__path__)"'
alias pysitepkgs='python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()"'
alias pytasks='grep --exclude-dir=.git -rEI "TODO|FIXME" . 2>/dev/null'
#alias ssh='ssh -R 10999:localhost:22'
alias nethack='telnet nethack.alt.org'
alias cmy='mysql -B -N -e'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
aptsearch(){ apt-cache search ^$1 | egrep --color=always "^[^-]+ "; }

PS1='\[\033[0;31m\]\u@newton\[\033[00m\]:\[\033[0;33m\]`pwd`\[\033[00m\]> '
