set nocompatible
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
"set autoindent
"set smartindent
set synmaxcol=4000
"setlocal spell spelllang=en

" use the below highlight group when displaying bad whitespace is desired.
highlight BadWhitespace ctermbg=red guibg=red
"
" Display tabs at the beginning of a line in Python mode as bad.
au BufRead,BufNewFile *.py,*.pyw match BadWhitespace /^\t\+/
" Make trailing whitespace be flagged as bad.
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

au BufNewFile *.py,*.pyw,*.c,*.h set fileformat=unix

" Color lines longer than 79 characters
highlight LongLine guibg=LightMagenta ctermbg=LightMagenta
au BufRead,BufNewFile *.py,*.pyw match LongLine /\%>79v.\+/

" For full syntax highlighting:
let python_highlight_all=1
syntax on

" Uncomment the following to have Vim jump to the last position when                                                       
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif
